# Generated by Django 3.2.6 on 2021-08-25 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=48)),
                ('address', models.CharField(max_length=48)),
                ('user_role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('TRADER', 'Trader'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20)),
                ('contact', models.IntegerField()),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('otp', models.IntegerField()),
                ('token', models.CharField(max_length=48)),
                ('otp_last_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=12, unique=True)),
                ('product_type', models.CharField(max_length=30, unique=True)),
                ('product_details', models.TextField(max_length=4000)),
                ('documents_path', models.TextField(max_length=1000)),
                ('is_approved', models.CharField(choices=[('Y', 'Approved'), ('P', 'Pending'), ('N', 'Rejected')], default='P', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
