# Generated by Django 3.2.6 on 2021-09-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-notified_date']},
        ),
    ]
