# Generated by Django 3.2.6 on 2021-09-02 03:57

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=40, validators=[products.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contact',
            field=models.IntegerField(validators=[products.validators.validate_contact]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=40, validators=[products.validators.validate_shop_name]),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('name', 'trader'), name='unique_for_trader'),
        ),
    ]
